### ISSUE TITLE
Add the Environment Configuration directive to new-system.sh

### ISSUE THREAD

**Issue by Noam-Alum** [Noam-Alum/AutoPilot#8]
Add the Environment Configuration directive to new-system.sh

It should contain 
 - Customize environment variables (e.g., export VAR=value)
 - Configure shell settings (e.g., ~/.bashrc or equivalent)

An example of the YAML format can be:
```yaml
Environment_Configuration:
   - Vars:
     Name: "noam"
     ms: "ssh noam@myserver.com"
   - Customize:
     Export_Vars:
       - VAR1: "value1"
       - VAR2: "value2"
       - PATH: "$PATH:/custom/path"
     Shell_Settings:
       - alias ll='ls -la'
       - alias gs='git status'
       - export EDITOR='vim'
       - export HISTSIZE=1000
       - export HISTFILESIZE=2000
       - PS1: "[\u@\h \W]\$ "  # Customize prompt
   - Startup_Files:
     - ~/.bashrc:
         Content:
           - "# Custom environment variables"
           - "export VAR1='value1'"
           - "export VAR2='value2'"
           - "# Aliases"
           - "alias ll='ls -la'"
           - "alias gs='git status'"
           - "# Shell settings"
           - "export EDITOR='vim'"
           - "export HISTSIZE=1000"
           - "export HISTFILESIZE=2000"
           - "PS1='[\u@\h \W]\$ '"
     - ~/.bash_profile:
         Content:
           - "# Load bashrc if it exists"
           - "[ -f ~/.bashrc ] && . ~/.bashrc"
```

Feel free to ask questions :smile:.
